apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mqtt-subscribe-moisture-sensor
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          containers:
          - name: mqtt-subscribe-moisture-sensor
            image: rio05docker/mqtt_subscriber_moisture_sensor:rpi3_test_21_07
            command: ["python",  "/home/root/scripts/MQTT_Client.py"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1