apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mqtt-publish-generic
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          containers:
          - name: mqtt-publish-generic
            image: rio05docker/mqtt_publisher_generic:rpi3_test_20_07
            command: ["python",  "/home/root/scripts/MQTT_Client.py"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1