apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt-module
  name: mqtt-svc
  namespace: mqtt
spec:
  type: NodePort
  ports:
     - port: 1833
       protocol: TCP
  selector:
    app: mqtt-module


