kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-pv-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

--- 

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-pv-log-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Mi
