apiVersion: v1
kind: Service
metadata:
  name: rpi-mosquitto
  labels:
    rioiotplatform: mosquitto
spec:
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  loadBalancerIP: 192.168.1.101
  selector:
    app: rpi-mosquitto
  type: LoadBalancer