apiVersion: v1
kind: Service
metadata:
  name: rpi-mosquitto
  labels:
    app: mosquitto
spec:
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  selector:
    app: rpi-mosquitto
