name: iot-home-ci

on:
  push: # Trigger when push on develop branch
   branches:
      - dev
        
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          ref: dev
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.4
        with:
          version: latest
        
      - name: Define variables
        run: echo Tags are > ${DOCKER_TAG}
        env:
          DAY: ${{ date -d "$D" '+%d'}}
          MONTH: ${{ date -d "$D" '+%m'}}
          DOCKER_TAG: rpi3_test_${DAY}_${MONTH}
      
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx #see: https://github.com/marketplace/actions/docker-buildx
        run: |
          docker buildx build \
            --tag rio05docker/mqtt_subscriber_moisture_sensor:${DOCKER_TAG} \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --file ./Arduino-Raspberry_MQTT/python/mqtt-subscriber-client/mqtt-subscriber-moisture/Dockerfile \
            ./Arduino-Raspberry_MQTT/python/mqtt-subscriber-client/mqtt-subscriber-moisture
      - 
        name: Publish to Docker Repository
        uses: opspresso/action-docker@v0.2.1
        with:
          name: rio05docker/mqtt_subscriber_moisture_sensor:${DOCKER_TAG}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
