name: iot-home-ci

on:
  push: # Trigger when push on develop branch
   branches:
      - dev
        
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          ref: dev
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.4
        with:
          version: latest
      
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - 
        name: Login to GitHub Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      -
        name: Run Buildx #see: https://github.com/marketplace/actions/docker-buildx
        run: |
          docker buildx build \
            --tag rio05docker/mqtt_subscriber_moisture_sensor:rpi3_test_${GITHUB_SHA} \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --file ./Arduino-Raspberry_MQTT/python/mqtt-subscriber-client/mqtt-subscriber-moisture/Dockerfile \
            ./Arduino-Raspberry_MQTT/python/mqtt-subscriber-client/mqtt-subscriber-moisture
   
